language: python
addons:
  apt:
    packages:
    - swig
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
before_install:
  - pip install codecov
  - pip install 'coverage<4'
script:
  - examples/test_examples.sh
after_success:
  - codecov
