language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
before_install:
  - pip install codecov
  - pip install 'coverage<4'
script:
  - coverage run ./pyrate --output build1.ninja example1.py
  - coverage run ./pyrate --output build2.ninja example2.py
  - cat build1.ninja build2.ninja
after_success:
  - codecov
